"""
HTML Report Generator Module.

Generates a self-contained HTML report for benchmark sessions.
The report can be opened locally without a web server.
"""

from pathlib import Path
from typing import List

from src.core.models import BenchmarkSession


class HTMLReporter:
    """Generate HTML reports for benchmark sessions.

    Creates a single-page HTML report that includes:
        - Session summary with key metrics
        - Embedded PNG charts
        - Links to CSV data files
        - Per-run details table

    The report is self-contained and can be opened offline.
    """

    # Expected chart filenames from ChartGenerator
    CHART_FILES = [
        "avg_fps_by_trial.png",
        "one_percent_low_by_trial.png",
        "frametime_p99_by_trial.png",
        "stutter_events_by_severity.png",
        "session_summary.png",
    ]

    # Expected CSV filenames from CSVExporter
    CSV_FILES = [
        "run_summaries.csv",
        "raw_frametimes.csv",
        "stutter_events.csv",
    ]

    def __init__(self, title: str = "GamePerfBench Report"):
        """Initialize the HTML reporter.

        Args:
            title: Title for the report page.
        """
        self.title = title

    def generate_report(
        self,
        session: BenchmarkSession,
        session_dir: Path,
    ) -> Path:
        """Generate an HTML report for a benchmark session.

        Args:
            session: BenchmarkSession containing run data.
            session_dir: Directory containing charts and CSVs.

        Returns:
            Path to the generated report.html file.
        """
        session_dir = Path(session_dir)

        # Find existing chart files
        existing_charts = self._find_existing_files(session_dir, self.CHART_FILES)

        # Find existing CSV files
        existing_csvs = self._find_existing_files(session_dir, self.CSV_FILES)

        # Generate HTML content
        html = self._build_html(session, existing_charts, existing_csvs)

        # Write report
        report_path = session_dir / "report.html"
        report_path.write_text(html, encoding="utf-8")

        return report_path

    def _find_existing_files(
        self,
        directory: Path,
        filenames: List[str],
    ) -> List[str]:
        """Find which files exist in the directory.

        Args:
            directory: Directory to check.
            filenames: List of filenames to look for.

        Returns:
            List of filenames that exist.
        """
        existing = []
        for filename in filenames:
            if (directory / filename).exists():
                existing.append(filename)
        return existing

    def _build_html(
        self,
        session: BenchmarkSession,
        charts: List[str],
        csvs: List[str],
    ) -> str:
        """Build the complete HTML document.

        Args:
            session: BenchmarkSession with data.
            charts: List of existing chart filenames.
            csvs: List of existing CSV filenames.

        Returns:
            Complete HTML string.
        """
        # Format timestamp
        ts_str = "N/A"
        if session.timestamp:
            ts_str = session.timestamp.strftime("%Y-%m-%d %H:%M:%S")

        # Get aggregate metrics
        agg = session.aggregate_metrics or {}
        variance = session.variance_result

        # Build HTML sections
        header_section = self._build_header_section(session, ts_str)
        summary_section = self._build_summary_section(agg, variance, len(session.runs))
        charts_section = self._build_charts_section(charts)
        downloads_section = self._build_downloads_section(csvs)
        runs_section = self._build_runs_section(session.runs)

        # Combine into full HTML
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.title} - {session.session_id}</title>
    {self._get_styles()}
</head>
<body>
    <div class="container">
        {header_section}
        {summary_section}
        {charts_section}
        {downloads_section}
        {runs_section}
        <footer>
            <p>Generated by GamePerfBench</p>
        </footer>
    </div>
</body>
</html>"""

        return html

    def _get_styles(self) -> str:
        """Get the inline CSS styles.

        Returns:
            Style tag with CSS.
        """
        return """<style>
        * {
            box-sizing: border-box;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        h1 {
            color: #2c3e50;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
        }
        h2 {
            color: #34495e;
            margin-top: 30px;
        }
        .header-info {
            background: #ecf0f1;
            padding: 15px;
            border-radius: 4px;
            margin-bottom: 20px;
        }
        .header-info p {
            margin: 5px 0;
        }
        .header-info strong {
            display: inline-block;
            width: 120px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #3498db;
            color: white;
        }
        tr:hover {
            background-color: #f5f5f5;
        }
        .summary-table {
            max-width: 500px;
        }
        .summary-table td:first-child {
            font-weight: bold;
            width: 60%;
        }
        .charts-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
            gap: 20px;
            margin: 20px 0;
        }
        .chart-container {
            text-align: center;
        }
        .chart-container img {
            max-width: 100%;
            height: auto;
            border: 1px solid #ddd;
            border-radius: 4px;
        }
        .downloads-list {
            list-style: none;
            padding: 0;
        }
        .downloads-list li {
            margin: 10px 0;
        }
        .downloads-list a {
            color: #3498db;
            text-decoration: none;
            padding: 8px 16px;
            background: #ecf0f1;
            border-radius: 4px;
            display: inline-block;
        }
        .downloads-list a:hover {
            background: #d5dbdb;
        }
        .status-passed {
            color: #27ae60;
            font-weight: bold;
        }
        .status-failed {
            color: #e74c3c;
            font-weight: bold;
        }
        footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #7f8c8d;
            font-size: 0.9em;
        }
    </style>"""

    def _build_header_section(self, session: BenchmarkSession, ts_str: str) -> str:
        """Build the header section HTML.

        Args:
            session: BenchmarkSession with metadata.
            ts_str: Formatted timestamp string.

        Returns:
            HTML string for header section.
        """
        return f"""<h1>{self.title}</h1>
        <div class="header-info">
            <p><strong>Session ID:</strong> {session.session_id}</p>
            <p><strong>Game:</strong> {session.game_name}</p>
            <p><strong>Preset:</strong> {session.preset_name}</p>
            <p><strong>Timestamp:</strong> {ts_str}</p>
        </div>"""

    def _build_summary_section(
        self,
        agg: dict,
        variance,
        num_runs: int,
    ) -> str:
        """Build the summary section HTML.

        Args:
            agg: Aggregate metrics dictionary.
            variance: VarianceCheckResult or None.
            num_runs: Number of runs in session.

        Returns:
            HTML string for summary section.
        """
        avg_fps = agg.get("avg_of_avg_fps", 0)
        one_pct_low = agg.get("avg_of_one_percent_low_fps", 0)
        worst_stutter = agg.get("worst_stutter_severity_over_session", "None")

        # Variance info
        variance_html = "<tr><td>Variance Check</td><td>N/A</td></tr>"
        if variance:
            status_class = "status-passed" if variance.passed else "status-failed"
            status_text = "PASSED" if variance.passed else "FAILED"
            variance_html = f"""<tr>
                <td>Variance Check</td>
                <td><span class="{status_class}">{status_text}</span></td>
            </tr>
            <tr>
                <td>CV</td>
                <td>{variance.cv_percent:.2f}%</td>
            </tr>
            <tr>
                <td>Max Deviation</td>
                <td>{variance.max_deviation:.2f} FPS</td>
            </tr>"""

        return f"""<h2>Summary</h2>
        <table class="summary-table">
            <tr>
                <td>Number of Runs</td>
                <td>{num_runs}</td>
            </tr>
            <tr>
                <td>Average FPS</td>
                <td>{avg_fps:.2f}</td>
            </tr>
            <tr>
                <td>1% Low FPS</td>
                <td>{one_pct_low:.2f}</td>
            </tr>
            <tr>
                <td>Worst Stutter</td>
                <td>{worst_stutter or "None"}</td>
            </tr>
            {variance_html}
        </table>"""

    def _build_charts_section(self, charts: List[str]) -> str:
        """Build the charts section HTML.

        Args:
            charts: List of existing chart filenames.

        Returns:
            HTML string for charts section.
        """
        if not charts:
            return """<h2>Charts</h2>
            <p>No charts available.</p>"""

        chart_html = ""
        for chart in charts:
            # Create readable title from filename
            title = chart.replace(".png", "").replace("_", " ").title()
            chart_html += f"""<div class="chart-container">
                <h3>{title}</h3>
                <img src="{chart}" alt="{title}">
            </div>\n"""

        return f"""<h2>Charts</h2>
        <div class="charts-grid">
            {chart_html}
        </div>"""

    def _build_downloads_section(self, csvs: List[str]) -> str:
        """Build the downloads section HTML.

        Args:
            csvs: List of existing CSV filenames.

        Returns:
            HTML string for downloads section.
        """
        if not csvs:
            return """<h2>Data Files</h2>
            <p>No data files available.</p>"""

        links_html = ""
        for csv in csvs:
            # Create readable label from filename
            label = csv.replace(".csv", "").replace("_", " ").title()
            links_html += f'<li><a href="{csv}" download>{label}</a></li>\n'

        return f"""<h2>Data Files</h2>
        <ul class="downloads-list">
            {links_html}
        </ul>"""

    def _build_runs_section(self, runs: list) -> str:
        """Build the per-run details section HTML.

        Args:
            runs: List of BenchmarkRun objects.

        Returns:
            HTML string for runs section.
        """
        if not runs:
            return """<h2>Run Details</h2>
            <p>No run data available.</p>"""

        rows_html = ""
        for run in runs:
            fps = run.fps_metrics or {}
            percs = run.percentiles or {}
            stutter = run.stutter_summary or {}

            avg_fps = fps.get("avg_fps", 0)
            one_pct = fps.get("one_percent_low_fps", 0)
            p99 = percs.get("p99_ms") or percs.get("p99_0_ms", 0)
            stutter_count = stutter.get("total_events", 0)

            rows_html += f"""<tr>
                <td>{run.run_id}</td>
                <td>{run.trial_index}</td>
                <td>{run.duration_seconds:.1f}</td>
                <td>{avg_fps:.2f}</td>
                <td>{one_pct:.2f}</td>
                <td>{p99:.2f}</td>
                <td>{stutter_count}</td>
            </tr>\n"""

        return f"""<h2>Run Details</h2>
        <table>
            <thead>
                <tr>
                    <th>Run ID</th>
                    <th>Trial</th>
                    <th>Duration (s)</th>
                    <th>Avg FPS</th>
                    <th>1% Low FPS</th>
                    <th>P99 (ms)</th>
                    <th>Stutters</th>
                </tr>
            </thead>
            <tbody>
                {rows_html}
            </tbody>
        </table>"""
